[build]
  publish = "front-end/"
  functions = "back-end/functions"  # Ruta correcta hacia las funciones dentro de la carpeta 'back-end'

[dev]
  functions = "back-end/functions"

[functions]
node_bundler = "esbuild"
timeout = 30  # Aumenta el tiempo a 30 segundos (valor máximo permitido por Netlify)