[build]
  publish = "front-end/html"
  functions = "back-end/functions"  # Ruta correcta hacia las funciones dentro de la carpeta 'back-end'

[dev]
  functions = "back-end/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
